---
#ansible-playbook clamav.yaml -i ../inventory --ask-pass --ask-become-pass
- name: Install ClamAV service
  hosts: test
  become: true
  tasks:
  - name: Dnf install zabbix-agent
    dnf:
      name: "{{ item }}"
      state: latest
    loop:
      - 'epel-release'
      - 'clamav'
      - 'clamd'
      - 'clamav-update'

  - name: Set permissions
    shell: "{{ item }}"
    loop:
      - ''setsebool -P antivirus_can_scan_system 1
      - 'sed -i 's/#LocalSocket \/run/LocalSocket \/run/g' /etc/clamd.d/scan.conf'

  - name: Copy conf
    copy:
      src: ../files/scan_config.conf
      dst: /usr/lib/systemd/system/freshclam.service
  
  - name: Start and enable freshclam
    ansible.builtin.service:
      name: freshclam
      state: restarted
      enabled: true

  - name: Start and enable clamav@scan
    ansible.builtin.service:
      name: clamd@scan
      state: restarted
      enabled: true